<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>isDisabled</key>
	<false/>
	<key>name</key>
	<string>WLA-DX</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#M6502</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#M65C02</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#M65816</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#decimal_number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hex_number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hex_number_h</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#binary_number</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\.)?\b(?i:24bit|accu|base|computesneschecksum|endemuvector|endnativevector|endsnes|fastrom|hirom|index|lorom|slowrom|smc|snesemuvector|snesheader|snesnativevector|16bit|8bit|asc|asciitable|asctable|asm|background|bank|block|br|breakpoint|byt|db|dbcos|dbm|dbrnd|dbsin|def|define|ds|dsb|dstruct|dsw|dw|dwcos|dwm|dwrnd|dwsin|else|emptyfill|endasm|endb|ende|endif|endm|endme|endr|endro|ends|endst|enum|equ|export|fail|fclose|fopen|fread|fsize|if|ifdef|ifdefm|ifeq|ifexists|ifgr|ifgreq|ifle|ifleeq|ifndef|ifndefm|ifneq|incbin|incdir|include|input|macro|memorymap|org|orga|outname|printt|printv|ramsection|redef|redefine|repeat|rept|rombankmap|rombanks|rombanksize|section|seed|shift|slot|struct|sym|symbol|unbackground|undef|undefine|word|cartridgetype|computegbchecksum|computegbcomplementcheck|licenseecodenew|licenseecodeold|ramsize|romdmg|romgbc|romsgb|name|computesmschecksum|sdsctag|smsta)\b</string>
			<key>name</key>
			<string>keyword.directive</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.semicolon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.asterisk</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[A-Za-z_][A-Za-z0-9_]*</string>
			<key>name</key>
			<string>variable.other.readwrite.assembly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\_[A-Za-z_][A-Za-z0-9_]*</string>
			<key>name</key>
			<string>variable.other.readwrite.instance.assembly</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.assembly</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>M6502</key>
		<dict>
			<key>match</key>
			<string>\b(?i:ADC|AND|ASL|BCC|BCS|BEQ|BIT|BMI|BNE|BPL|BRK|BVC|BVS|CLC|CLD|CLI|CLV|CMP|CPX|CPY|DEC|DEX|DEY|EOR|INC|INX|INY|JMP|JSR|LDA|LDX|LDY|LSR|NOP|ORA|PHA|PHP|PLA|PLP|ROL|ROR|RTI|RTS|SBC|SEC|SED|SEI|STA|STX|STY|TAX|TAY|TSX|TXA|TXS|TYA)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.6502</string>
		</dict>
		<key>M65816</key>
		<dict>
			<key>match</key>
			<string>\b(?i:BRL|COP|JML|JSL|MVN|MVP|PEA|PEI|PER|PHB|PHD|PHK|PLB|PLD|REP|RTL|SEP|TCD|TCS|TDC|TSC|TXY|TYX|WDM|XBA|XCE)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65816</string>
		</dict>
		<key>M65C02</key>
		<dict>
			<key>match</key>
			<string>\b(?i:BRA|PHX|PHY|PLX|PLY|STP|STZ|TRB|TSB|WAI)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65c02</string>
		</dict>
		<key>binary_number</key>
		<dict>
			<key>match</key>
			<string>%[01]+</string>
			<key>name</key>
			<string>constant.numeric.binary</string>
		</dict>
		<key>decimal_number</key>
		<dict>
			<key>match</key>
			<string>\b([0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.decimal</string>
		</dict>
		<key>hex_number</key>
		<dict>
			<key>match</key>
			<string>\$[A-Fa-f0-9]+</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<key>hex_number_h</key>
		<dict>
			<key>match</key>
			<string>\b([0-9]+)h\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.assembly.65816.wla-dx</string>
    <key>uuid</key>
    <string>08DD72DB-881D-44A6-BC16-5DF9BA21F189</string>
</dict>
</plist>
